export type Project = {
  slug: string;
  index: string;
  title: string;
  /** Дизайн-студия объекта. Обязательно показываем — особенно «Маши Марченко». */
  designer: string;
  kind: string;
  location: string;
  area: string;
  /** Стоимость работ. Уточняется у Василия, обновляется раз в 3–4 дня. */
  price: string;
  duration: string;
  /** Описание объекта из «Текст для сайта.docx». Пустое — текст ещё не прислали. */
  description: string;
  cover: string;
  thumb: string;
  photoCount: number;
  images: string[];
};

/* Порядок портфолио: сначала дома, затем квартиры, коммерческие помещения — в конец. */
export const projects: Project[] = [
  {
    slug: "dom-mechty",
    index: "01",
    title: "Дом вашей мечты за полгода",
    designer: "Лаборатория дизайна",
    kind: "Частный дом",
    location: "",
    area: "290 м²",
    price: "14 050 000 ₽",
    duration: "8 месяцев",
    description:
      "Заказчик — семья с детьми, главная задача была сдать дом до 1 сентября. Работали зимой: для просушки полов докупали электрогенератор и осушители. Дом трёхэтажный — пока полгода устанавливали лестницу, работать на верхних ярусах было непросто, поэтому на 3 этаж наняли отдельную бригаду маляров и инженеров. Отдельное испытание — гипсокартонные потолки с закарнизным светом и скрытыми треками, а на мансарде — потолок из 6000 светодиодов с эффектом звёздного неба. Проект в неоклассическом стиле создан студией «Лаборатория дизайна»: строгие формы, светлая палитра, натуральные фактуры.",
    cover: "/images/objects/1/01.webp",
    thumb: "/images/objects/1/thumb.webp",
    photoCount: 111,
    images: [
      "/images/objects/1/01.webp",
      "/images/objects/1/02.webp",
      "/images/objects/1/03.webp",
      "/images/objects/1/04.webp",
      "/images/objects/1/05.webp",
      "/images/objects/1/06.webp",
      "/images/objects/1/07.webp",
      "/images/objects/1/08.webp",
      "/images/objects/1/09.webp",
      "/images/objects/1/10.webp",
      "/images/objects/1/11.webp",
      "/images/objects/1/12.webp",
      "/images/objects/1/13.webp",
      "/images/objects/1/14.webp",
      "/images/objects/1/15.webp",
      "/images/objects/1/16.webp",
      "/images/objects/1/17.webp",
      "/images/objects/1/18.webp",
      "/images/objects/1/19.webp",
      "/images/objects/1/20.webp",
      "/images/objects/1/21.webp",
      "/images/objects/1/22.webp",
      "/images/objects/1/23.webp",
      "/images/objects/1/24.webp",
    ],
  },
  {
    slug: "zhk-renessans-78",
    index: "02",
    title: "Квартира в ЖК «Ренессанс» за 4 месяца",
    designer: "Маши Марченко",
    kind: "Квартира",
    location: "",
    area: "78 м²",
    price: "3 120 000 ₽",
    duration: "5 месяцев",
    description:
      "Проект студии Маши Марченко — классический стиль, бежево-пудровая палитра, тёплое дерево. Основная сложность — стыковка разных напольных покрытий, крупноформатная плитка под камень, подгонка встроенной мебели. В ванной — сочетание мрамора, дерева и стекла со скрытой подсветкой.",
    cover: "/images/objects/6/01.jpg",
    thumb: "/images/objects/6/thumb.jpg",
    photoCount: 9,
    images: [
      "/images/objects/6/01.jpg",
      "/images/objects/6/02.jpg",
      "/images/objects/6/03.jpg",
      "/images/objects/6/04.jpg",
      "/images/objects/6/05.jpg",
      "/images/objects/6/06.jpg",
      "/images/objects/6/07.jpg",
      "/images/objects/6/08.jpg",
      "/images/objects/6/09.jpg",
    ],
  },
  {
    slug: "klinika-paradny-kvartal",
    index: "03",
    title: "Клиника в ЖК «Парадный квартал»",
    designer: "LO DESIGN",
    kind: "Клиника",
    location: "",
    area: "212 м²",
    price: "7 520 000 ₽",
    duration: "4 месяца",
    description:
      "Проект студии «LO DESIGN» — минимализм, бежево-песочная палитра. Основная сложность — геометрия арок и ниш: высокая точность стыковки поверхностей, скрытая подсветка вдоль архитектурных линий. В интерьере — терракотовые кресла и акценты из дерева.",
    cover: "/images/objects/4/15.webp",
    thumb: "/images/objects/4/thumb.webp",
    photoCount: 36,
    images: [
      "/images/objects/4/01.webp",
      "/images/objects/4/02.webp",
      "/images/objects/4/03.webp",
      "/images/objects/4/04.webp",
      "/images/objects/4/05.webp",
      "/images/objects/4/06.webp",
      "/images/objects/4/07.webp",
      "/images/objects/4/08.webp",
      "/images/objects/4/09.webp",
      "/images/objects/4/10.webp",
      "/images/objects/4/11.webp",
      "/images/objects/4/12.webp",
      "/images/objects/4/13.webp",
      "/images/objects/4/14.webp",
      "/images/objects/4/15.webp",
      "/images/objects/4/16.webp",
      "/images/objects/4/17.webp",
      "/images/objects/4/18.webp",
      "/images/objects/4/19.webp",
      "/images/objects/4/20.webp",
      "/images/objects/4/21.webp",
      "/images/objects/4/22.webp",
      "/images/objects/4/23.webp",
      "/images/objects/4/24.webp",
    ],
  },
  {
    slug: "dom-vsevolozhsk",
    index: "04",
    title: "Дом во Всеволожске",
    designer: "",
    kind: "Частный дом",
    location: "Всеволожск, Ленинградская область",
    area: "220 м²",
    price: "9 820 000 ₽",
    duration: "9 месяцев",
    description:
      "Двухэтажный дом в области сдали за 9 месяцев. Главная сложность — минимализм: он требует особенно аккуратной работы маляров, потому что окна высотой 6 метров высвечивают любую царапину или бугорок. Стены проверяли под лампой Лосева. Строили сразу на нескольких этажах, пока устанавливали лестницу. Современный стиль построен на сочетании камня и натурального дерева, смягчающего строгую архитектуру.",
    cover: "/images/objects/2/01.webp",
    thumb: "/images/objects/2/thumb.webp",
    photoCount: 12,
    images: [
      "/images/objects/2/01.webp",
      "/images/objects/2/02.webp",
      "/images/objects/2/03.webp",
      "/images/objects/2/04.webp",
      "/images/objects/2/05.webp",
      "/images/objects/2/06.webp",
      "/images/objects/2/07.webp",
      "/images/objects/2/08.webp",
      "/images/objects/2/09.webp",
      "/images/objects/2/10.webp",
      "/images/objects/2/11.webp",
      "/images/objects/2/12.webp",
    ],
  },
  {
    slug: "zhk-piter",
    index: "05",
    title: "Квартира в ЖК «Питер»",
    designer: "Маши Марченко",
    kind: "Квартира",
    location: "",
    area: "80 м²",
    price: "3 210 000 ₽",
    duration: "5 месяцев",
    description:
      "Квартира 80 м² для хозяйки с детьми, с непростыми дизайнерскими элементами — уложились в 5 месяцев без спешки. Основная сложность — состыковка шестиугольной плитки с рваными краями и паркета, где важен был каждый миллиметр. Отдельно выверяли фотообои и панели: мебель требовала идеально ровных поверхностей и прямых углов. Главный элемент интерьера — прозрачная раздвижная перегородка между спальней и кухней, создающая эффект приватности. Дизайн — студия Маши Марченко: минимализм с тёплыми фактурами, дерево и золотистый свет.",
    cover: "/images/objects/3/01.webp",
    thumb: "/images/objects/3/thumb.webp",
    photoCount: 63,
    images: [
      "/images/objects/3/01.webp",
      "/images/objects/3/02.webp",
      "/images/objects/3/03.webp",
      "/images/objects/3/04.webp",
      "/images/objects/3/05.webp",
      "/images/objects/3/06.webp",
      "/images/objects/3/07.webp",
      "/images/objects/3/08.webp",
      "/images/objects/3/09.webp",
      "/images/objects/3/10.webp",
      "/images/objects/3/11.webp",
      "/images/objects/3/12.webp",
      "/images/objects/3/13.webp",
      "/images/objects/3/14.webp",
      "/images/objects/3/15.webp",
      "/images/objects/3/16.webp",
      "/images/objects/3/17.webp",
      "/images/objects/3/18.webp",
      "/images/objects/3/19.webp",
      "/images/objects/3/20.webp",
      "/images/objects/3/21.webp",
      "/images/objects/3/22.webp",
      "/images/objects/3/23.webp",
      "/images/objects/3/24.webp",
    ],
  },
  {
    slug: "stomatologiya",
    index: "06",
    title: "Стоматология за 3 недели",
    designer: "Маши Марченко",
    kind: "Стоматология",
    location: "",
    area: "210 м²",
    price: "8 650 000 ₽",
    duration: "23 рабочих дня",
    description:
      "Дизайн студии Маши Марченко — светлые оттенки, мрамор, золотистые акценты. Точная укладка крупно- и мелкоформатной плитки, многоуровневое освещение. Отдельная сложность — замена электрики в сжатые сроки без повреждения старой: проверяли каждый кабель, тестирование с субподрядчиками каждые 3 дня.",
    cover: "/images/objects/5/01.webp",
    thumb: "/images/objects/5/thumb.webp",
    photoCount: 20,
    images: [
      "/images/objects/5/01.webp",
      "/images/objects/5/02.webp",
      "/images/objects/5/03.webp",
      "/images/objects/5/04.webp",
      "/images/objects/5/05.webp",
      "/images/objects/5/06.webp",
      "/images/objects/5/07.webp",
      "/images/objects/5/08.webp",
      "/images/objects/5/09.webp",
      "/images/objects/5/10.webp",
      "/images/objects/5/11.webp",
      "/images/objects/5/12.webp",
      "/images/objects/5/13.webp",
      "/images/objects/5/14.webp",
      "/images/objects/5/15.webp",
      "/images/objects/5/16.webp",
      "/images/objects/5/17.webp",
      "/images/objects/5/18.webp",
      "/images/objects/5/19.webp",
      "/images/objects/5/20.webp",
    ],
  },
  {
    slug: "zhk-leningrad",
    index: "07",
    title: "Квартира в ЖК «Ленинград»",
    designer: "Маши Марченко",
    kind: "Квартира",
    location: "",
    area: "125 м²",
    price: "4 950 000 ₽",
    duration: "6,5 месяцев",
    description:
      "",
    cover: "/images/objects/7/01.webp",
    thumb: "/images/objects/7/thumb.webp",
    photoCount: 38,
    images: [
      "/images/objects/7/01.webp",
      "/images/objects/7/02.webp",
      "/images/objects/7/03.webp",
      "/images/objects/7/04.webp",
      "/images/objects/7/05.webp",
      "/images/objects/7/06.webp",
      "/images/objects/7/07.webp",
      "/images/objects/7/08.webp",
      "/images/objects/7/09.webp",
      "/images/objects/7/10.webp",
      "/images/objects/7/11.webp",
      "/images/objects/7/12.webp",
      "/images/objects/7/13.webp",
      "/images/objects/7/14.webp",
      "/images/objects/7/15.webp",
      "/images/objects/7/16.webp",
      "/images/objects/7/17.webp",
      "/images/objects/7/18.webp",
      "/images/objects/7/19.webp",
      "/images/objects/7/20.webp",
      "/images/objects/7/21.webp",
      "/images/objects/7/22.webp",
      "/images/objects/7/23.webp",
      "/images/objects/7/24.webp",
    ],
  },
  {
    slug: "zhk-renessans-75",
    index: "08",
    title: "Квартира в ЖК «Ренессанс»",
    designer: "Маши Марченко",
    kind: "Квартира",
    location: "",
    area: "75 м²",
    price: "3 480 000 ₽",
    duration: "5 месяцев",
    description:
      "",
    cover: "/images/objects/8/01.webp",
    thumb: "/images/objects/8/thumb.webp",
    photoCount: 37,
    images: [
      "/images/objects/8/01.webp",
      "/images/objects/8/02.webp",
      "/images/objects/8/03.webp",
      "/images/objects/8/04.webp",
      "/images/objects/8/05.webp",
      "/images/objects/8/06.webp",
      "/images/objects/8/07.webp",
      "/images/objects/8/08.webp",
      "/images/objects/8/09.webp",
      "/images/objects/8/10.webp",
      "/images/objects/8/11.webp",
      "/images/objects/8/12.webp",
      "/images/objects/8/13.webp",
      "/images/objects/8/14.webp",
      "/images/objects/8/15.webp",
      "/images/objects/8/16.webp",
      "/images/objects/8/17.webp",
      "/images/objects/8/18.webp",
      "/images/objects/8/19.webp",
      "/images/objects/8/20.webp",
      "/images/objects/8/21.webp",
      "/images/objects/8/22.webp",
      "/images/objects/8/23.webp",
      "/images/objects/8/24.webp",
    ],
  },
  {
    slug: "dom-artemyagi",
    index: "09",
    title: "Дом в Артемиагах",
    designer: "",
    kind: "Частный дом",
    location: "Артемиагах, Ленинградская область",
    area: "270 м²",
    price: "Уточняется",
    duration: "10 месяцев",
    description:
      "Объект достался по сарафанному радио — заказчик купил землю, построил коробку и искал команду на отделку. Сроки были открытыми, без жёстких рамок: работали спокойно, без халтуры, на всех 270 квадратах. Дом сдан ровно через 10 месяцев.",
    cover: "/images/objects/9/01.jpg",
    thumb: "/images/objects/9/thumb.jpg",
    photoCount: 9,
    images: [
      "/images/objects/9/01.jpg",
      "/images/objects/9/02.jpg",
      "/images/objects/9/03.jpg",
      "/images/objects/9/04.jpg",
      "/images/objects/9/05.jpg",
      "/images/objects/9/06.jpg",
      "/images/objects/9/07.jpg",
      "/images/objects/9/08.jpg",
      "/images/objects/9/09.jpg",
    ],
  },
];

export function getProject(slug: string) {
  return projects.find((project) => project.slug === slug);
}
